/* Published examples only. Platform projects waiting for access stay in the private registry. */
const fabProjects=[
{id:'still',category:'graphics',previewType:'graphic',name:'STILL',kind:'Учебные карточки товара',platform:'Композиция / SVG / PNG',image:'samples/creative/cards/01-cover.png',url:'samples/creative/#cards',intro:'Три карточки термобутылки: первый экран, детали и характеристики.',problem:'Сделать товар понятным без перегруженной инфографики.',solution:'Три макета 1200 × 1600, оригинальная предметная визуализация и редактируемые надписи.',features:['Обложка товара','Карточка деталей','Карточка характеристик','Три PNG и три исходника SVG'],checks:['Откройте три макета.','Скачайте PNG и исходник SVG.','Надписи в SVG редактируются отдельно от изображения.'],limits:'Самостоятельная учебная работа, не заказ магазина. Бренд, товар и характеристики заданы вымышленным брифом. Предметное изображение создано с ИИ. Исходник SVG, не PSD.'},
{id:'mora',category:'graphics',previewType:'graphic',name:'MORA',kind:'Учебная презентация',platform:'PowerPoint / предметная визуализация',image:'samples/creative/mora/slide-01.png',url:'samples/creative/#mora',intro:'Восемь слайдов косметической коллекции с редактируемыми текстами и таблицей.',problem:'Представить четыре продукта единым набором и отдельно показать каждый формат.',solution:'Презентация 16:9, оригинальные предметные изображения, четыре продуктовых слайда и настоящая таблица PowerPoint.',features:['Восемь слайдов','Редактируемый PPTX','Нативная таблица ассортимента','PNG каждого слайда'],checks:['Посмотрите все восемь слайдов.','Скачайте PPTX.','Измените подпись и ячейку таблицы в редакторе презентаций.'],limits:'Вымышленная линейка и учебный бриф. Изображения созданы с ИИ; лечебных свойств и результатов продаж нет. Растровые изображения не становятся редактируемой 3D-моделью.'},
{id:'thumbnails',category:'graphics',previewType:'graphic',name:'Три обложки YouTube',kind:'Самостоятельные концепции',platform:'Графика / SVG / PNG',image:'samples/creative/thumbnails/01-keyboard.png',url:'samples/creative/#thumbnails',intro:'Техника, рабочее место и ИИ: три разные визуальные подачи в формате 1280 × 720.',problem:'Сделать тему ролика заметной и сохранить читабельный заголовок.',solution:'Контрастная техническая обложка, тёплая редакционная композиция и графичный ИИ-сюжет.',features:['Три самостоятельные обложки','Размер 1280 × 720','Редактируемые заголовки','PNG и SVG'],checks:['Откройте три композиции.','Сравните заголовки в уменьшенном виде.','Скачайте исходник и замените текст.'],limits:'Не работы для существующего канала. CTR не измерялся. Изображения сгенерированы; текст оформлен отдельно.'},
{id:'rift',category:'graphics',previewType:'graphic',name:'RIFT',kind:'Учебная концепция упаковки',platform:'Упаковка / рекламная графика',image:'samples/creative/packaging/01-campaign.png',url:'samples/creative/#packaging',intro:'Кофейная упаковка, лицевая этикетка и квадратный пост в одном направлении.',problem:'Перенести узнаваемую визуальную идею с упаковки на рекламный материал.',solution:'Кобальтовая палитра, крупная типографика, предметная визуализация и отдельная редактируемая этикетка.',features:['Предметная рекламная композиция','Лицевая этикетка SVG','Квадратный пост','PNG для просмотра'],checks:['Посмотрите упаковку и отдельную этикетку.','Откройте квадратный пост.','Скачайте редактируемый SVG.'],limits:'Дизайн-концепция, не производственная развёртка. Нет проверки маркировки, штрихкода и типографии. Надписи на предметном изображении растровые; отдельная этикетка редактируется.'},
{id:'peremena',category:'content',previewType:'graphic',name:'Перемена',kind:'Учебный набор текстов',platform:'Тексты / контент-план / сценарий',image:'samples/creative/copy-preview.png',url:'samples/creative/coworking.html',intro:'Главная коворкинга, две услуги, три поста, сценарий видео и недельный план.',problem:'Из одного брифа подготовить разные материалы без повторения одной рекламы.',solution:'Полный набор текстов для сайта и социальных площадок с единым тоном.',features:['Первый экран сайта','Описание двух услуг','Три поста','Сценарий короткого видео','Недельный план'],checks:['Прочитайте исходный бриф.','Сравните сайт, посты и сценарий.','Скачайте текст в Markdown.'],limits:'Коворкинг, условия и цены вымышлены. Это пример копирайтинга, не действующее место и не опубликованная рекламная кампания.'},
{id:'wordpress',category:'web',name:'Поле',kind:'Учебный WordPress-журнал',platform:'WordPress / PHP / SQLite',image:'assets/pole-home.webp',url:'wordpress-pole.html',intro:'Оригинальная редакционная тема, рубрики, поиск и настоящее редактирование в CMS.',problem:'Добавлять и менять публикации без редактирования HTML.',solution:'Своя тема WordPress, три рубрики, шесть статей, медиатека и отдельная роль редактора.',features:['Публикации и рубрики WordPress','Поиск по содержимому','Изображения в медиатеке','Мобильная версия и режим чтения','Создание и правка через штатную панель'],checks:['Откройте страницу демонстрации: там реальные снимки сайта и редактора.','На компьютере владельца можно открыть работающий журнал.','Выберите рубрику и найдите заметку поиском.','В панели проверены создание, сохранение изменения и возврат статьи в черновики.'],limits:'Учебная локальная установка настоящего WordPress. Не HTML-имитация CMS, но публичный хостинг пока не настроен. Нет вымышленных клиентов, показателей аудитории и рассылки. Секреты и база вне публичного сайта.'},
{id:'nerv',category:'tools',name:'Нерв',kind:'Учебный продукт',platform:'HTML / CSS / JavaScript',image:'assets/nerv-home.png',url:'demos/nerv/',intro:'Технический сайт и консоль: нагрузка, отказ узла, очередь и восстановление.',problem:'Показать технический продукт через работающий сценарий, а не набор неподвижных цифр.',solution:'Отдельная маркетинговая страница, векторная топология и детерминированная модель двух рабочих узлов.',features:['Регулировка потока запросов','Отказ и восстановление узла','Расчёт очереди и отклонений','История задержки и журнал событий','Пауза и сброс опыта'],checks:['Откройте консоль.','Поднимите поток до 180 запросов/с и отключите узел B.','Очередь растёт; при заполнении возникают отклонения.','Верните B и снизьте поток до 70/с: очередь разгружается.','Проверьте паузу и сброс.'],limits:'Вымышленный продукт. Данные рассчитываются в браузере. Нет настоящей телеметрии, подключения инфраструктуры, учётных записей и общего сервера. Не RAG и не ИИ-сервис.'},
{id:'landing',category:'web',name:'ЖК «Верхний сад»',kind:'Учебный лендинг',platform:'HTML / CSS / JS',image:'brand/shots/zk.jpg',url:'zk/',intro:'Жилой комплекс: атмосфера места, выбор планировки и подробная композиция.',problem:'Показать жильё через пространство и сценарии жизни, а не одну сетку преимуществ.',solution:'Разделы о комплексе, планировки, адаптивная подача и подбор.',features:['Планировки и визуальная подача','Описание комплекса','Сценарий подбора','Мобильная версия'],checks:['Перейдите к планировкам.','Проверьте подбор и навигацию.','Посмотрите мобильную версию.'],limits:'Комплекс вымышленный. Адреса, цены и сроки учебные. Не сайт реального застройщика, заявки и продажи не подтверждены.'},
{id:'lead-desk',category:'tools',name:'Пульт обращений',kind:'Интерактивный прототип',platform:'HTML / JS',image:'assets/lead-desk-20261008.webp',url:'demos/lead-desk/',intro:'Очередь с дедлайнами, поиск, карточка обращения и экспорт.',problem:'Не терять следующее действие по входящему обращению.',solution:'Добавление и редактирование обращений, статусы, сроки и выгрузка CSV.',features:['Поиск и фильтрация','Карточки и сроки','Сохранение в браузере','CSV текущей выборки','Проверка повреждённых данных','Предупреждение об ошибке сохранения'],checks:['Добавьте вымышленное обращение.','Поменяйте статус и обновите страницу.','Найдите запись поиском.','Выберите статус и выгрузите CSV: в файле только показанные записи.'],limits:'Локальная демонстрация, не внедрение amoCRM или Битрикс24. Нет общего сервера и прав сотрудников. Только вымышленные данные.'},
{id:'diority',category:'shops',name:'Diority',kind:'Собственный магазин',platform:'Веб',image:'brand/shots/diority.jpg',url:'https://diority.com/',intro:'Каталог цифровых товаров с отдельными карточками и расчётом стоимости.',problem:'Собрать ассортимент в понятный каталог и показать сумму до оформления.',solution:'Категории, карточки товаров, калькулятор номинала и страницы условий.',features:['Категории и карточки товаров','Расчёт суммы','Контакты и условия'],checks:['Откройте категорию и карточку.','Измените номинал в калькуляторе.','Прочитайте условия покупки.'],limits:'Собственный проект, не заказ стороннего клиента. Показан интерфейс и структура; оплата и автоматическая выдача этой проверкой не подтверждены. Показателей продаж не заявляю.'},
{id:'repair',category:'tools',name:'Кабинет сервиса ремонта',kind:'Интерактивный прототип',platform:'HTML / JS',image:'portfolio/repair-interface.png',url:'demos/repair-console/',intro:'Заявки, ответственный и следующий шаг в одном окне.',problem:'Показать очередь ремонта и сроки следующего действия.',solution:'Карточки устройств, поиск, фильтры и сохранение изменений в браузере.',features:['Очередь и карточка заказа','Поиск и статусы','Ответственный','Локальное сохранение'],checks:['Измените статус и ответственного.','Сохраните карточку.','Найдите заявку поиском.','Обновите страницу.'],limits:'Нет общего сервера, авторизации и совместной работы. Это не готовая CRM. Используйте только вымышленные данные.'},
{id:'estimate',category:'tools',name:'Смета за минуту',kind:'Интерактивное демо',platform:'HTML / JS',image:'portfolio/estimate-interface.png',url:'demos/estimate/',intro:'Состав работ, количество, скидка и печатное предложение.',problem:'Считать небольшое предложение без отдельной таблицы.',solution:'Редактируемые позиции с пересчётом суммы и печатной версией.',features:['Добавление и удаление работ','Стоимость и скидка','Сохранение в браузере','Печать'],checks:['Измените количество первой позиции с 1 на 2.','При примере и скидке 10% итог меняется с 35 100 на 45 900 ₽.','Добавьте работу и откройте печать.'],limits:'Не счёт и не платёжный сервис. Нет CRM; PDF получается через печать браузера. Суммы в демо не расценки Fabrestra.'},
{id:'autostamp',category:'automation',name:'AutoStamp',kind:'Учебный инструмент',platform:'Python / Word / Excel',image:'assets/autostamp-proof.svg',url:'samples/autostamp/',intro:'Одни реквизиты для подготовленных документов Word и Excel.',problem:'Не перепечатывать название, шифр и автора в разных документах.',solution:'Программа заполняет закладки Word и именованные диапазоны Excel из общего набора данных, сохраняет исходники и журнал.',features:['Общий набор реквизитов','Карта полей','Копии исходных шаблонов','Журнал обработки'],checks:['Откройте учебный набор.','Сравните реквизиты с готовыми Word и Excel.','Исходные шаблоны не изменены.'],limits:'Только подготовленные Word/Excel. Нет AutoCAD, сканов, подписей и сборки PDF. Соответствие ГОСТ не проверено. Данные вымышлены.'},
{id:'booking',category:'web',name:'Тихая мастерская',kind:'Учебный сайт',platform:'HTML / JS',image:'assets/booking-v3.png',url:'demos/booking/',intro:'Выбор услуги, мастера и времени без длинной переписки.',problem:'Провести посетителя от выбора занятия до подтверждения записи.',solution:'Услуги, расписание, локальная запись и отмена.',features:['Услуги и специалисты','Свободное время','Запись и отмена','Сохранение локальных записей'],checks:['Выберите услугу, мастера и день.','Запишитесь с вымышленным именем.','Обновите страницу.','Отмените запись: время снова доступно.'],limits:'Вымышленная мастерская. Нет настоящего бронирования, уведомлений и сервера. Записи только в этом браузере.'},
{id:'restaurant',category:'web',name:'Соль и хлеб',kind:'Учебный многостраничный сайт',platform:'HTML / JS',image:'assets/restaurant-v3.png',url:'demos/restaurant/',intro:'Меню, выбор блюд с расчётом суммы и демонстрационная бронь.',problem:'Дать гостю посмотреть меню и выбрать время посещения.',solution:'Отдельные страницы главной, меню, блюда и бронирования.',features:['Категории меню','Карточки блюд','Выбор, количество и сумма','Сохранение выбора в браузере','Форма бронирования','Адаптивная композиция'],checks:['Откройте меню и выберите категорию.','Добавьте блюдо дважды: количество и сумма меняются.','Обновите страницу: выбор сохраняется.','Уберите одну порцию.','Перейдите к блюду и проверьте состав.','Проверьте обязательные поля бронирования.'],limits:'Вымышленный ресторан. Форма не отправляет заявку и не резервирует стол. Меню и цены учебные.'},
{id:'architecture',category:'web',name:'Слой',kind:'Учебный сайт бюро',platform:'HTML / JS',image:'assets/architecture-v3.png',url:'demos/architecture/',intro:'Каталог концепций с отдельными страницами и планами.',problem:'Показать проект подробнее, чем одной картинкой в сетке.',solution:'Каталог, подробные страницы, концептуальная визуализация, схемы и обращение по проекту.',features:['Фильтр назначения','Страницы проектов','Схематичные планы','Контекстная форма'],checks:['Выберите жилые проекты.','Откройте страницу и план.','В форме обращения должен быть выбран этот проект.'],limits:'Вымышленное бюро. Схемы не рабочая документация, форма без сервера. Не заявляю работу архитектора.'}
];
function fabEl(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function fabLink(text,url,cls){const a=fabEl('a',text,cls);a.href=url;return a;}
const fabCoverArt={
  booking:{art:'demos/booking/ceramics-v2.webp',label:'Керамика / запись на занятие'},
  restaurant:{art:'demos/restaurant/bread-v2.webp',label:'Ресторан / меню и выбор блюд'},
  architecture:{art:'demos/architecture/courtyard-v2.webp',label:'Архитектура / каталог концепций'}
};
function fabCover(p,visual){
  visual.classList.add('project-cover','cover-'+p.id);
  visual.setAttribute('aria-label','Посмотреть работу: '+p.name);
  if(p.previewType==='graphic'){
    const poster=fabEl('img',undefined,'cover-poster');poster.src=p.image;poster.alt=p.name+': готовый пример';poster.loading='lazy';visual.append(poster,fabEl('span',p.kind,'badge'));return;
  }
  const art=fabCoverArt[p.id];
  if(art){const photo=fabEl('img',undefined,'cover-photo');photo.src=art.art;photo.alt='';photo.loading='lazy';visual.append(photo);}
  const frame=fabEl('span',undefined,'cover-browser'),bar=fabEl('span',undefined,'cover-browser-bar');
  bar.append(fabEl('span','● ● ●'),fabEl('span','ПРЕДПРОСМОТР'));
  const screen=fabEl('img',undefined,'cover-screen');screen.src=p.image;screen.alt=p.name+(p.id==='autostamp'?': схема работы инструмента':': снимок интерфейса');screen.loading='lazy';
  frame.append(bar,screen);visual.append(frame);
  if(art){const caption=fabEl('span',undefined,'cover-caption');caption.append(fabEl('small',art.label),fabEl('strong',p.name));visual.append(caption);}
  visual.append(fabEl('span',p.kind,'badge'));
}
function fabInitCatalog(){
  const grid=document.querySelector('#catalog-grid');if(!grid)return;
  const filters=document.querySelector('#catalog-filters');
  function render(cat){
    grid.replaceChildren();const items=fabProjects.filter(p=>cat==='all'||p.category===cat);
    for(const p of items){
      const card=fabEl('article',undefined,'card'),visual=fabLink('',`case.html?id=${p.id}`,'visual');fabCover(p,visual);
      const body=fabEl('div',undefined,'cardbody');body.append(fabEl('p',p.platform,'eyebrow'),fabEl('h2',p.name),fabEl('p',p.intro),fabLink('Описание и пример ↗',`case.html?id=${p.id}`,'textlink'));
      card.append(visual,body);grid.append(card);
    }
    if(!items.length){const e=fabEl('div',undefined,'empty-state');e.append(fabEl('h2','Кейс пока не опубликован'),fabEl('p','Настоящая интеграция появится после проверки. Макеты CRM не выдаём за внедрения.'));grid.append(e);}
    document.querySelector('#filter-status').textContent='Показано работ: '+items.length;
  }
  for(const [id,label] of [['all','Все работы'],['web','Сайты'],['shops','Магазины'],['crm','CRM'],['automation','Автоматизация'],['tools','Инструменты'],['graphics','Графика и презентации'],['content','Тексты']]){
    const n=fabProjects.filter(p=>id==='all'||p.category===id).length,b=fabEl('button',`${label} (${n})`);b.type='button';b.setAttribute('aria-pressed',String(id==='all'));b.classList.toggle('active',id==='all');
    b.addEventListener('click',()=>{filters.querySelectorAll('button').forEach(o=>{o.classList.toggle('active',o===b);o.setAttribute('aria-pressed',String(o===b));});render(id);});filters.append(b);
  }
  render('all');
}
document.querySelectorAll('[data-project-cover]').forEach(visual=>{const p=fabProjects.find(p=>p.id===visual.dataset.projectCover);if(p){visual.replaceChildren();fabCover(p,visual);}});
function fabInitCase(){const root=document.querySelector('#case-root');if(!root)return;const p=fabProjects.find(p=>p.id===new URLSearchParams(location.search).get('id'));if(!p){root.append(fabEl('h1','Проект не найден'),fabLink('Вернуться к работам','portfolio.html'));return;}document.title=p.name+' / Fabrestra';const hero=fabEl('section',undefined,'casehero');hero.append(fabEl('p',p.platform,'eyebrow'),fabEl('h1',p.name),fabEl('p',p.intro,'lead'),fabEl('p',p.kind,'status'));const actions=fabEl('div',undefined,'caseactions');actions.append(fabLink(p.id==='wordpress'?'Демонстрация и панель ↗':p.id==='autostamp'?'Учебный набор ↗':'Открыть пример ↗',p.url,'button'),fabLink('Обсудить похожую задачу','https://t.me/fabrestra','button secondary'));hero.append(actions);const picture=fabEl('figure',undefined,'casepicture'),img=fabEl('img');img.src=p.image;img.alt=p.name;picture.append(img);const grid=fabEl('div',undefined,'casegrid');for(const [title,body,list] of [['Задача',p.problem,false],['Решение',p.solution,false],['Что сделано',p.features,true],['Как проверить',p.checks,true],['Границы примера',p.limits,false]]){const panel=fabEl('section',undefined,'panel'+(title==='Границы примера'?' wide boundaries':''));panel.append(fabEl('h2',title));if(list){const ul=fabEl(title==='Как проверить'?'ol':'ul');body.forEach(s=>ul.append(fabEl('li',s)));panel.append(ul);}else panel.append(fabEl('p',body));grid.append(panel);}root.append(hero,picture,grid,fabEl('p',['diority','repair','estimate','landing','booking','restaurant','architecture','lead-desk','nerv','wordpress'].includes(p.id)?'Обложка: снимок существующего интерфейса.':'Обложка: графическая композиция, не скриншот внедрения. Рабочий пример — по ссылке.','auditdate'));}
fabInitCatalog();fabInitCase();

