(()=>{'use strict';
const root=document.getElementById('mini-content');if(!root)return;
let tab='works',category='all',saved=[];
try{const value=JSON.parse(localStorage.getItem('fabrestra-mini-saved-v1'));saved=Array.isArray(value)?value.filter(id=>fabProjects.some(p=>p.id===id)):[];}catch{}
const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const link=(text,href,cls)=>{const e=make('a',text,cls);e.href=href;return e;};
function saveButton(p){const b=make('button',saved.includes(p.id)?'Сохранено':'Сохранить','mini-save');b.type='button';b.setAttribute('aria-pressed',String(saved.includes(p.id)));b.onclick=()=>{saved=saved.includes(p.id)?saved.filter(id=>id!==p.id):[...saved,p.id];try{localStorage.setItem('fabrestra-mini-saved-v1',JSON.stringify(saved));}catch{}b.textContent=saved.includes(p.id)?'Сохранено':'Сохранить';b.setAttribute('aria-pressed',String(saved.includes(p.id)));if(tab==='saved')render();};return b;}
function detail(p){root.replaceChildren();const back=make('button','← К списку','mini-back');back.onclick=render;const box=make('section',undefined,'mini-detail'),img=make('img');img.src=p.image;img.alt=p.name;box.append(make('p',p.kind,'mini-status'),make('h1',p.name),img,make('p',p.intro),make('h2','Что работает'));const ul=make('ul');p.features.forEach(s=>ul.append(make('li',s)));box.append(ul,make('h2','Границы примера'),make('p',p.limits),link('Открыть рабочий пример ↗',p.url,'mini-action'),saveButton(p),link('Обсудить похожую задачу ↗','https://t.me/fabrestra','mini-action'));root.append(back,box);root.scrollIntoView({block:'start'});}
function render(){root.replaceChildren();if(tab==='works'||tab==='saved'){root.append(make('h1',tab==='saved'?'Отложенные работы':'Можно попробовать.'));if(tab==='works'){const filters=make('div',undefined,'mini-filters');for(const [key,title] of [['all','Все'],['web','Сайты'],['shops','Магазины'],['tools','Инструменты'],['automation','Автоматизация']]){const b=make('button',title);b.setAttribute('aria-pressed',String(key===category));b.onclick=()=>{category=key;render();};filters.append(b);}root.append(filters);}
const projects=fabProjects.filter(p=>tab==='saved'?saved.includes(p.id):(category==='all'||p.category===category));root.append(make('p','Показано работ: '+projects.length,'mini-status'));if(!projects.length)root.append(make('p','Сохраните интересную работу, чтобы вернуться к ней позже. Избранное хранится в этом браузере.','mini-empty'));
for(const p of projects){const card=make('article',undefined,'mini-card'),img=make('img');img.src=p.image;img.alt=p.name;img.loading='lazy';const row=make('div',undefined,'mini-row'),open=make('button','Разобрать ↗','mini-open');open.onclick=()=>detail(p);row.append(open,saveButton(p));card.append(img,make('h2',p.name),make('p',p.kind,'mini-status'),make('p',p.intro),row);root.append(card);}}
else if(tab==='services'){root.append(make('h1','Начать с одной задачи.'),make('p','Цена зависит от согласованного состава. Домен, сервер и платные сервисы отдельно.'),link('Страница услуги / от 10 000 ₽','service-web.html','mini-action'),link('Документы из таблицы / от 3 000 ₽','service-automation.html','mini-action'),link('Бот для заявок / от 8 000 ₽','services.html','mini-action'),link('Ручная проверка / по сценариям','service-testing.html','mini-action'),link('Все условия и расценки ↗','services.html','mini-action'));}
else root.append(make('h1','Обсудим задачу.'),make('p','Арсен Галустьян / Fabrestra. Пришлите описание, материалы и желаемый срок.'),link('Telegram / @fabrestra ↗','https://t.me/fabrestra','mini-action'),link('arsen@fabrestra.com ↗','mailto:arsen@fabrestra.com','mini-action'),link('Биржи и полный список контактов ↗','contacts.html','mini-action'));
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(o=>o.setAttribute('aria-pressed',String(o===b)));render();});render();
})();
